blacklist = [
    "__popup__",
    "large",
]

strict_mode = true

[default_session]
startup_command = "start-tmux-session"

# [[session]]
# path = "~/Repos/satellite"
# startup_command = "nvim ."
# windows = [ "ex", "git", "tin" ]

[[session]]
name = "generic"
path = "~"
startup_command = "tmux set status off"

[[session]]
name = "large"
path = "~"
startup_command = "tmux set status off"

[[session]]
name = "_dots"
path = "~/.dots"

[[session]]
name = "Downloads"
path = "~/Downloads"

[[session]]
name = "Notes"
path = "~"
startup_command  = "nvim NOTES.md"

[[session]]
name = "llm"
path = "~/.dots/opt/llm"
startup_command  = "ai"

# [[window]]
# name = "vi"
# startup_script = "nvim ."
#
# [[window]]
# name = "git"
#
# [[window]]
# name = "ex"
#
# [[window]]
# name = "tin"
